# Generated by Django 5.2.1 on 2026-09-29 18:36

import apps.redaction.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RedactionJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pii_types_detected', models.JSONField(blank=True, default=list)),
                ('pii_count', models.IntegerField(default=0)),
                ('redacted_file', models.FileField(blank=True, null=True, upload_to=apps.redaction.models.redacted_file_path)),
                ('redaction_report', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redaction_jobs', to='documents.document')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redaction_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Redaction Job',
                'db_table': 'pramaan_redaction_jobs',
                'ordering': ['-created_at'],
            },
        ),
    ]
