# Generated by Django 5.2.1 on 2026-09-29 16:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_hash', models.CharField(help_text='Hash stored at upload time', max_length=64)),
                ('computed_hash', models.CharField(help_text='Hash re-computed at verify time', max_length=64)),
                ('is_tampered', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='documents.document')),
                ('verified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifications_done', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Verification Result',
                'verbose_name_plural': 'Verification Results',
                'db_table': 'pramaan_verifications',
                'ordering': ['-verified_at'],
            },
        ),
    ]
