# Generated by Django 5.2.1 on 2026-09-29 17:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustodyChain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_location', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('REGISTERED', 'Registered'), ('IN_TRANSFER', 'In Transfer'), ('WITH_CFSL', 'With CFSL Lab'), ('WITH_COURT', 'With Court'), ('RETURNED', 'Returned to IO'), ('ARCHIVED', 'Archived')], default='REGISTERED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_holder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custody_holdings', to=settings.AUTH_USER_MODEL)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='custody_chain', to='documents.document')),
            ],
            options={
                'verbose_name': 'Custody Chain',
                'db_table': 'pramaan_custody_chains',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustodyTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_location', models.CharField(blank=True, max_length=255)),
                ('to_location', models.CharField(blank=True, max_length=255)),
                ('transfer_reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Confirmation'), ('CONFIRMED', 'Confirmed'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('document_hash_at_transfer', models.CharField(blank=True, max_length=64)),
                ('custody_chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='custody.custodychain')),
                ('from_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_sent', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Custody Transfer',
                'db_table': 'pramaan_custody_transfers',
                'ordering': ['-initiated_at'],
            },
        ),
    ]
