# Generated by Django 5.2.1 on 2026-09-29 16:08

import apps.documents.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('case_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('filename', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=apps.documents.models.document_upload_path)),
                ('file_type', models.CharField(blank=True, max_length=100)),
                ('file_size', models.BigIntegerField(default=0)),
                ('sha256_hash', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('REGISTERED', 'Registered'), ('VERIFIED', 'Verified'), ('TAMPERED', 'Tampered'), ('ARCHIVED', 'Archived')], default='REGISTERED', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'db_table': 'pramaan_documents',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
