# Generated by Django 5.2.1 on 2026-09-29 17:31

import apps.certificates.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('verification', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceCertificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('certificate_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('certificate_type', models.CharField(choices=[('INTEGRITY', 'Integrity Certificate'), ('CUSTODY_CHAIN', 'Chain of Custody Certificate'), ('COURT_EXPORT', 'Court Export Certificate')], default='INTEGRITY', max_length=20)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to=apps.certificates.models.certificate_upload_path)),
                ('sha256_of_pdf', models.CharField(blank=True, max_length=64)),
                ('is_valid', models.BooleanField(default=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='documents.document')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_certificates', to=settings.AUTH_USER_MODEL)),
                ('verification_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='verification.verificationresult')),
            ],
            options={
                'verbose_name': 'Evidence Certificate',
                'db_table': 'pramaan_certificates',
                'ordering': ['-generated_at'],
            },
        ),
    ]
